# Generated by Django 4.2.9 on 2024-01-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_reset_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reset',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
